### ISSUE TITLE
PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by larslemos** [UCSF-IGHS/openmrs-esm-ohri#211]
While Issuing a PR, as a Team to ensure proper documentation and best practices. Follow the below Check List
What is the Scope of the PR
- [ ] Include Screenshots or GIFs of the UI changes ?
- [ ] Link to the Issue (eg: at https:https://ohri.atlassian.net/jira/software/projects/OHRI/boards/1?selectedIssue=OHRI-)
- [ ] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] All new and existing tests passed

Did you?
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes

Collaboration
- [ ] Assign 2+ colleagues to your PR 
- [ ] Ensure the CI Checks Pass before Merge
- [ ] Follow up with updating the Ticket associated to the Task

**Comment by smallgod** [comment]
thanks @larslemos
